[package]
name = "nestforge-kafka"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
readme = "../../README.md"
description = "Kafka transport support for NestForge built on rskafka"
keywords = ["rust", "kafka", "transport", "microservices", "nestforge"]
categories = ["network-programming", "web-programming"]

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
nestforge-core = { version = "1.10.0", path = "../nestforge-core", registry = "gitea" }
nestforge-microservices = { version = "1.10.0", path = "../nestforge-microservices", registry = "gitea" }
rskafka = "0.6"
futures = "0.3"
chrono = { version = "0.4", default-features = false, features = ["clock"] }

[dev-dependencies]
tokio = { workspace = true }
